import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs';
import TanstackProvider from '@/providers/tanstack.provider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Crypto tracking',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <TanstackProvider>
            <main className='max-w-2xl mx-auto my-0 px-2 pt-4 relative'>
              {children}
            </main>
          </TanstackProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
