import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ClerkProvider, currentUser } from '@clerk/nextjs';
import TanstackProvider from '@/providers/tanstack.provider';
import { Header } from '@/components/header';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Crypto tracking',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const clerkUser = await currentUser();
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <TanstackProvider>
            <main className='max-w-2xl mx-auto my-0 pl-2 pr-4 py-4 relative'>
              {/* @ts-expect-error Server Component */}
              <Header clerkUser={clerkUser} />
              {children}
            </main>
          </TanstackProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
